/**
 * Infographic SVG Generator
 * 
 * Produces professional, visually rich SVG infographics with:
 * - Gradient header with title and subtitle
 * - Icon circles with category badges
 * - Data visualization bars and metrics
 * - Proper typography hierarchy
 * - Color-coded sections
 * - Source attribution footer
 */

// ==================== TYPES ====================

export interface InfographicSection {
  headline: string;
  content: string;
  icon: string;
  dataPoint?: string;
  color: string;
  percentage?: number;
}

export interface InfographicParams {
  title: string;
  subtitle?: string;
  sections: InfographicSection[];
  colorScheme?: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    bg: string;
    cardBg: string;
  };
  stats?: Array<{ label: string; value: string; icon: string }>;
}

// ==================== SVG GENERATORS ====================

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + ' ' + word).length > maxChars && currentLine) {
      lines.push(currentLine.trim());
      currentLine = word;
    } else {
      currentLine += ' ' + word;
    }
  }
  if (currentLine.trim()) lines.push(currentLine.trim());
  return lines;
}

export function generateInfographicSVG(params: InfographicParams): string {
  const {
    title,
    subtitle = 'Generated by NTRO GenAI Platform',
    sections,
    colorScheme = {
      primary: '#1a1a2e',
      secondary: '#16213e',
      accent: '#e94560',
      text: '#ffffff',
      bg: '#0f3460',
      cardBg: '#1a1a3e',
    },
    stats = [],
  } = params;

  // Layout constants
  const width = 1080;
  const headerHeight = 280;
  const sectionHeight = 180;
  const statsBarHeight = stats.length > 0 ? 140 : 0;
  const footerHeight = 80;
  const totalHeight = headerHeight + statsBarHeight + sections.length * sectionHeight + footerHeight + 40;

  // ==================== HEADER ====================
  const header = `
  <defs>
    <linearGradient id="headerGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${colorScheme.primary}"/>
      <stop offset="50%" style="stop-color:${colorScheme.secondary}"/>
      <stop offset="100%" style="stop-color:${colorScheme.bg}"/>
    </linearGradient>
    <linearGradient id="accentGrad" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:${colorScheme.accent}"/>
      <stop offset="100%" style="stop-color:${colorScheme.accent}88"/>
    </linearGradient>
    <filter id="shadow" x="-5%" y="-5%" width="110%" height="120%">
      <feDropShadow dx="0" dy="4" stdDeviation="8" flood-color="#000000" flood-opacity="0.3"/>
    </filter>
    <filter id="glow">
      <feGaussianBlur stdDeviation="3" result="blur"/>
      <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>

  <!-- Background -->
  <rect width="${width}" height="${totalHeight}" fill="${colorScheme.bg}"/>

  <!-- Header -->
  <rect width="${width}" height="${headerHeight}" fill="url(#headerGrad)"/>
  <rect width="${width}" height="4" y="${headerHeight - 4}" fill="url(#accentGrad)"/>

  <!-- Header content -->
  <text x="${width / 2}" y="80" font-size="42" fill="${colorScheme.text}" font-weight="800" text-anchor="middle" font-family="Inter, -apple-system, sans-serif" letter-spacing="-0.5">${escapeXml(title)}</text>

  <text x="${width / 2}" y="120" font-size="16" fill="${colorScheme.text}99" text-anchor="middle" font-family="Inter, -apple-system, sans-serif">${escapeXml(subtitle)}</text>

  <!-- Accent line -->
  <rect x="${width / 2 - 60}" y="140" width="120" height="3" rx="1.5" fill="${colorScheme.accent}"/>

  <!-- Decorative dots -->
  <circle cx="60" cy="60" r="4" fill="${colorScheme.accent}" opacity="0.4"/>
  <circle cx="80" cy="80" r="2" fill="${colorScheme.text}" opacity="0.2"/>
  <circle cx="${width - 60}" cy="60" r="4" fill="${colorScheme.accent}" opacity="0.4"/>
  <circle cx="${width - 80}" cy="80" r="2" fill="${colorScheme.text}" opacity="0.2"/>

  <!-- Classification badge -->
  <rect x="${width / 2 - 80}" y="160" width="160" height="28" rx="14" fill="${colorScheme.accent}20" stroke="${colorScheme.accent}" stroke-width="1"/>
  <text x="${width / 2}" y="179" font-size="11" fill="${colorScheme.accent}" font-weight="600" text-anchor="middle" font-family="Inter, sans-serif" letter-spacing="2">CONFIDENTIAL</text>

  <!-- Key metrics in header -->
  <g transform="translate(0, 210)">
    ${sections.slice(0, 3).map((s, i) => {
      const x = 120 + i * 320;
      return `
    <rect x="${x}" y="0" width="280" height="55" rx="10" fill="${colorScheme.text}08" stroke="${colorScheme.text}15" stroke-width="1"/>
    <text x="${x + 16}" y="24" font-size="20" font-weight="800" fill="${s.color}" font-family="Inter, sans-serif">${escapeXml(s.dataPoint || '—')}</text>
    <text x="${x + 16}" y="44" font-size="10" fill="${colorScheme.text}88" font-family="Inter, sans-serif">${escapeXml(s.headline.substring(0, 30))}</text>`;
    }).join('\n    ')}
  </g>`;

  // ==================== STATS BAR ====================
  const statsBar = stats.length > 0 ? `
  <!-- Stats Bar -->
  <g transform="translate(0, ${headerHeight})">
    <rect width="${width}" height="${statsBarHeight}" fill="${colorScheme.primary}cc"/>
    <rect width="${width}" height="1" y="0" fill="${colorScheme.text}10"/>
    ${stats.map((stat, i) => {
      const x = 60 + i * ((width - 120) / stats.length);
      const statWidth = (width - 120) / stats.length;
      return `
    <g transform="translate(${x}, 20)">
      <text x="${statWidth / 2}" y="25" font-size="22" text-anchor="middle" fill="${colorScheme.text}">${stat.icon}</text>
      <text x="${statWidth / 2}" y="55" font-size="28" font-weight="800" text-anchor="middle" fill="${colorScheme.accent}" font-family="Inter, sans-serif">${escapeXml(stat.value)}</text>
      <text x="${statWidth / 2}" y="78" font-size="11" text-anchor="middle" fill="${colorScheme.text}88" font-family="Inter, sans-serif">${escapeXml(stat.label)}</text>
      ${i < stats.length - 1 ? `<line x1="${statWidth}" y1="10" x2="${statWidth}" y2="${statsBarHeight - 30}" stroke="${colorScheme.text}15" stroke-width="1"/>` : ''}
    </g>`;
    }).join('')}
  </g>` : '';

  // ==================== SECTIONS ====================
  const sectionsOffset = headerHeight + statsBarHeight;
  const sectionsSVG = sections.map((section, i) => {
    const y = sectionsOffset + i * sectionHeight;
    const contentLines = wrapText(section.content, 80);
    const hasProgress = section.percentage !== undefined;

    return `
  <!-- Section ${i + 1}: ${section.headline} -->
  <g transform="translate(60, ${y})">
    <!-- Card background -->
    <rect x="0" y="0" width="960" height="${sectionHeight - 20}" rx="16" fill="${colorScheme.cardBg}" stroke="${section.color}30" stroke-width="1" filter="url(#shadow)"/>
    
    <!-- Color accent bar -->
    <rect x="0" y="0" width="6" height="${sectionHeight - 20}" rx="3" fill="${section.color}"/>
    
    <!-- Icon circle -->
    <circle cx="55" cy="55" r="30" fill="${section.color}20" stroke="${section.color}50" stroke-width="1.5"/>
    <text x="55" y="63" font-size="26" text-anchor="middle">${section.icon}</text>
    
    <!-- Headline -->
    <text x="100" y="42" font-size="20" font-weight="700" fill="${colorScheme.text}" font-family="Inter, sans-serif">${escapeXml(section.headline)}</text>
    
    <!-- Content lines -->
    ${contentLines.slice(0, 3).map((line, li) =>
      `<text x="100" y="${68 + li * 20}" font-size="13" fill="${colorScheme.text}cc" font-family="Inter, sans-serif">${escapeXml(line.substring(0, 85))}</text>`
    ).join('\n    ')}
    
    <!-- Data point / Progress bar -->
    ${hasProgress ? `
    <g transform="translate(680, 25)">
      <text x="120" y="20" font-size="36" font-weight="800" fill="${section.color}" text-anchor="end" font-family="Inter, sans-serif">${section.percentage}%</text>
      <rect x="0" y="35" width="120" height="8" rx="4" fill="${colorScheme.text}15"/>
      <rect x="0" y="35" width="${120 * (section.percentage || 0) / 100}" height="8" rx="4" fill="${section.color}"/>
    </g>` : section.dataPoint ? `
    <g transform="translate(700, 20)">
      <text x="100" y="22" font-size="32" font-weight="800" fill="${section.color}" text-anchor="end" font-family="Inter, sans-serif">${escapeXml(section.dataPoint)}</text>
      <rect x="40" y="38" width="60" height="4" rx="2" fill="${section.color}40"/>
    </g>` : ''}
    
    <!-- Category badge -->
    <rect x="100" y="${sectionHeight - 55}" width="80" height="22" rx="11" fill="${section.color}15"/>
    <text x="140" y="${sectionHeight - 40}" font-size="9" font-weight="600" fill="${section.color}" text-anchor="middle" font-family="Inter, sans-serif" letter-spacing="1">SECTION ${i + 1}</text>
  </g>`;
  }).join('\n');

  // ==================== FOOTER ====================
  const footerY = totalHeight - footerHeight;
  const footer = `
  <!-- Footer -->
  <g transform="translate(0, ${footerY})">
    <line x1="60" y1="0" x2="${width - 60}" y2="0" stroke="${colorScheme.text}15" stroke-width="1"/>
    <text x="60" y="30" font-size="10" fill="${colorScheme.text}55" font-family="Inter, sans-serif">Blockchain-verified content • Hash-chain integrity assured</text>
    <text x="${width - 60}" y="30" font-size="10" fill="${colorScheme.text}55" text-anchor="end" font-family="Inter, sans-serif">${new Date().toISOString().split('T')[0]} • NTRO GenAI Platform</text>
    <rect x="60" y="45" width="40" height="2" rx="1" fill="${colorScheme.accent}" opacity="0.4"/>
  </g>`;

  // ==================== ASSEMBLE ====================
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${totalHeight}" width="${width}" height="${totalHeight}">
  ${header}
  ${statsBar}
  ${sectionsSVG}
  ${footer}
</svg>`;
}